---
- hosts: devenv
  remote_user: aholmback

  vars:
      user: aholmback
      ansible_become_pass: password
      home: /home/{{ user }}
      tmpdir: "{{ home }}/tmp"
      bindir: "{{ home }}/bin"

  tasks:
      - include: tasks/distupgrade.yml
      - include: tasks/ngrok.yml
      - include: tasks/docker.yml
      - include: tasks/node-essentials.yml
      - include: tasks/pip.yml
      - include: tasks/vim.yml
      - include: tasks/git.yml
      - include: tasks/ansible.yml
      - include: tasks/build-tools.yml
      - include: tasks/shell.yml


