---
- hosts: dev

  # http://docs.ansible.com/ansible/playbooks_roles.html
  vars:
      user: aholmback
      ansible_become_pass: password
      home: /home/{{ user }}
      tmpdir: "{{ home }}/tmp"
      bindir: "{{ home }}/bin"

  roles:
      - ide
