---
- name: "Install build-tools apt packages"
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - build-essential
    - python-dev
    - python3-dev
    - libffi-dev
    - libpq-dev


