---
# https://docs.docker.com/engine/installation/linux/ubuntu/#recommended-extra-packages-for-trusty-1404
- name: "Install docker dependencies"
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - apt-transport-https
    - linux-image-virtual

# https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository
- name: "Add docker repository key"
  become: yes
  apt_key:
      id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
      url: https://download.docker.com/linux/ubuntu/gpg

- name: "Add docker repository"
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu yakkety stable"
    state: present

- name: "Install docker"
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - docker-ce

# http://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo
- name: "Add docker group"
  become: yes
  group:
    name: docker
    state: present

- name: "Add user {{ user }} to group docker"
  become: yes
  user:
    name: "{{ user }}"
    groups: docker
    append: yes

- name: "Restart docker"
  become: yes
  service: name=docker state=restarted

# https://docs.docker.com/compose/install/
- name: "Install docker-compose"
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/1.11.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
