---
- name: "Install ngrok dependencies"
  become: yes
  apt: name={{ item }} state=latest
  with_items:
      - unzip

- name: "Install ngrok"
  become: yes
  unarchive:
      src: "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip"
      dest: /usr/local/bin/
      remote_src: yes

- name: "Install ngrok authtoken"
  command: /usr/local/bin/ngrok authtoken YYU3TGTkWmhcK6JgaC8w_28kWUHCTMvcBUeTdxPZHC


