---
- name: Set authorized key took from file
  become: yes
  become_user: "{{ item }}"
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  with_items:
    - alex
    - root

- name: Set root password (aszf1umA2bauJ5Ju552mF4rRMmhAyz5X)
  become: yes
  user:
    name: root
    password: $6$YZ7Tz6F2oS.rmK$gOUGxCz2l2sDEbazss9L8lnKBwoKkKfNkU6AWSzFNlZPhiSGEmvoEVT3vSOM0Nf/GbKMn7fzJDf/agu3VPRG61

- name: Copy sshd_config
  become: yes
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config

- name: Copy ssh-keys
  copy:
    src: ~/.ssh/id_rsa
    dest: "{{ home }}/.ssh/"
    mode: 0600

- name: Add backports
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb http://ftp.debian.org/debian stretch-backports main"

- name: Update system
  become: yes
  apt:
    update_cache: true
    upgrade: dist

- name: Update/install debian packages
  become: yes
  apt:
    pkg: "{{item}}"
    state: latest
    default_release: stretch-backports
  with_items:
    - bash-completion
    - less
    - vim
    - git
    - unzip
    - tmux
    - ncdu
    - python
    - python-pip
    - silversearcher-ag

- name: Update/install global pip packages
  become: yes
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - ansible

- name: Configure git
  template:
    src: .gitconfig
    dest: "{{ home }}/.gitconfig"

- name: Configure bash
  template:
    src: .bash_profile
    dest: "{{ home }}/.bash_profile"

- name: Create directory for vim plugins
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ home }}/.vim/bundle"

- name: Configure vim
  template:
    src: vimrc
    dest: "{{ home }}/.vim/"

- name: Install vim plugins
  git:
      repo: https://github.com/{{ item.account }}/{{ item.name }}.git
      dest: "{{ home }}/.vim/bundle/{{ item.name }}"
  with_items:
      - { name: vim-pathogen, account: tpope }
      - { name: nerdtree, account: scrooloose }
      - { name: ctrlp.vim, account: kien }
      - { name: ale, account: w0rp }
      - { name: ack.vim, account: mileszs }
      - { name: vim-colorschemes, account: flazz }
      - { name: vim-javascript, account: pangloss }
      - { name: vim-mustache-handlebars, account: mustache }

- name: Install ngrok
  become: yes
  unarchive:
      src: "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip"
      dest: /usr/local/bin/
      remote_src: yes

- name: Install ngrok authtoken
  command: /usr/local/bin/ngrok authtoken YYU3TGTkWmhcK6JgaC8w_28kWUHCTMvcBUeTdxPZHC

- name: Create/verify ~/.ssh
  file:
    path: "{{ item }}"
    state: directory
  with_items:
      - "{{ home }}/.ssh"

