---
- name: "Install vim packages"
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - neovim

- name: "Ensure directories exists for vim"
  file: path={{ item }} state=directory
  with_items:
    - "{{ home }}/.config/nvim/bundle"

- name: "Configure vim"
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
      - { src: templates/init.vim, dest: "{{ home }}/.config/nvim/init.vim", }

- name: "Install vim plugins"
  git:
      repo: https://github.com/{{ item.account }}/{{ item.name }}.git
      dest: "{{ home }}/.config/nvim//bundle/{{ item.name }}"
  with_items:
      - { name: vim-pathogen, account: tpope, }
      - { name: nerdtree, account: scrooloose, }
      - { name: vim-vue, account: posva, }
